include: package:very_good_analysis/analysis_options.2.3.0.yaml

analyzer: 
  exclude: 
    - lib/core/l10n/localizations.g.dart
    - test/**.mocks.dart

linter:
  rules:
    public_member_api_docs: false
    cascade_invocations: false
    avoid_dynamic_calls: false