targets:
  $default:
    builders:
      json_serializable:
        generate_for:
          include:
            - lib/features/auth/data/models/**.dart
            - lib/features/auth/domain/entities/**.dart
            - lib/data/*/models/**.dart
            - lib/domain/*/entities/**.dart
        options:
          any_map: false
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: snake
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true
      mockito|mockBuilder:
        generate_for:
          - test/**.dart
      flutter_sheet_localization_generator|flutter_sheet_localization:
        enabled: true
        generate_for:
          - lib/core/l10n/**.dart
